---
language: ruby
bundler_args: --without production
rvm:
  - 2.0.0
deploy:
  provider: heroku
  app: osusume
  api_key:
  - secure: |-
      EKTxHfQLm71DCNG72a94gJ6MQdh86NBNeEg3KXvuMqTuy8Vo73t9vXZJ5R0n
      HJ9k5Yy+X32qVl17cj6wRPqwB1S/5U18hCz2ndWPCpWc6jxiOsIPUzPa3RC1
      qKX/o7NCrExx4Npn02R2QfQpHOp+pIpkSFcbB2k0jqpmoIYqPF4=
  on:
    rvm: 2.0.0
notifications:
  webhooks:
    urls:
      - http://travis-ci.herokuapp.com/computer_science
    on_success: never
    on_failure: always
    on_start: false
